# Generated by Django 3.1 on 2020-08-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliationstatus',
            options={'verbose_name_plural': 'Affiliation statuses'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='politicalparty',
            options={'verbose_name_plural': 'Political parties'},
        ),
        migrations.AddField(
            model_name='politicalparty',
            name='acronym',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
