# Generated by Django 3.1 on 2020-08-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20200806_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
