# Generated by Django 3.1 on 2020-08-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20200806_2210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Affiliation',
            new_name='PartyAffiliation',
        ),
        migrations.CreateModel(
            name='InstitutionAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.institution')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.person')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.affiliationstatus')),
            ],
        ),
    ]
