# Generated by Django 3.1 on 2020-08-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_institution_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstitutionDetail',
            new_name='PartyDetail',
        ),
        migrations.RemoveField(
            model_name='partydetail',
            name='person',
        ),
        migrations.AddField(
            model_name='partydetail',
            name='party',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='story.politicalparty'),
            preserve_default=False,
        ),
    ]
