# Generated by Django 3.1 on 2020-08-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20200806_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='alias',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
