# Generated by Django 3.1 on 2020-08-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_institution_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='political_party',
            field=models.BooleanField(default=False),
        ),
    ]
