# Generated by Django 3.1 on 2020-08-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_institutiondetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoliticalParty',
            new_name='OldPoliticalParty',
        ),
        migrations.CreateModel(
            name='PoliticalPartyAffiliation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('story.institutionaffiliation',),
        ),
        migrations.CreateModel(
            name='PoliticalPartyDetail',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('story.institutiondetail',),
        ),
    ]
