# Generated by Django 3.1 on 2020-08-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0017_auto_20200807_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='alias',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
