# Generated by Django 3.1 on 2020-08-07 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_auto_20200807_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='story.person'),
        ),
    ]
