# Generated by Django 3.1 on 2020-08-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0023_auto_20200807_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionaffiliation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='story.person'),
        ),
    ]
