# Generated by Django 3.1 on 2020-08-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0024_auto_20200807_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tagged_institutions',
            field=models.ManyToManyField(blank=True, related_name='tagged_institutions', to='story.Institution'),
        ),
        migrations.AddField(
            model_name='event',
            name='tagged_persons',
            field=models.ManyToManyField(blank=True, related_name='tagged_events', to='story.Person'),
        ),
        migrations.AlterField(
            model_name='title',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='story.person'),
        ),
    ]
